### ISSUE TITLE
Auto-Merged PR even though PR was not reviewed and checks did not pass

### ISSUE THREAD

**Issue by menny** [pascalgn/automerge-action#61] opened 2020-03-10 16:52 UTC
This is the PR: https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/2114

![image](https://user-images.githubusercontent.com/481272/76337405-b1430a80-62cd-11ea-9258-09a0b744f9d8.png)

I have branch protection enabled:
![image](https://user-images.githubusercontent.com/481272/76337534-e3ed0300-62cd-11ea-8228-b89e368b44e5.png)

I'm using github-actions to run PR checks/verifications.
I'm using a personal token (since I need the PR merge to trigger the push-to-master checks).

**Comment by karfau** [comment] 2020-03-10 18:32
I think there might be some missing information:
- the checks you are showing are showing the status of the merge commit on the master branch and all the checks are green by now.
- the checks for the last commit that has been force pushed to the branch are also all green including the required `master-green-requirement`:

![image](https://user-images.githubusercontent.com/135657/76346712-bb80fb00-6305-11ea-95e1-c5966097dc48.png)

If you still believe this is an issue and not just misreading all the different informations, you will need to provide more details or another example.

**Comment by menny** [comment] 2020-03-10 20:14
What other information? I provided a screenshot of the auto-merge which was done, and in the same screenshot you can see that not all checks were done, specifically the `master-green-requirement`

**Comment by menny** [comment] 2020-03-10 20:16
https://github.com/AnySoftKeyboard/AnySoftKeyboard/runs/498444642?check_suite_focus=true

**Comment by karfau** [comment] 2020-03-10 20:23
Am I right that the github action `master-green-requirement` is only executed on branches or PRs?
The reason why it is not even listed in your sceenshot although it is required for PR to land, is that your screenshot shows the github actions that are (at the time of your screenshot) being executed against the merge commit on the master branch. At least that is what it looks like for me.

Another issue might be that if your branch protection is not also forcing Admins to require those checks, and your personal token that you are using is for an admin, it might be able to skip the tests. But There is not enough information in this issue to confirm this.

**Comment by pascalgn** [comment] 2020-04-01 12:48
I think this is not yet fixed, or at least it's not clear what the cause for the problem is. However, it's a long time since there was any activity in this issue, so I will close it for now. If you have any new information or need any help, feel free to reopen this issue!

**Closed by pascalgn** 2020-04-01 12:48 UTC
