### ISSUE TITLE
Failed to merge PR: Resource not accessible by integration

### ISSUE THREAD

**Issue by rosolko** [pascalgn/automerge-action#150] opened 2021-05-06 07:20 UTC
Hello, @pascalgn 

Recently I've setup automerge action using such confg:
```yaml
name: automerge

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  check_suite:
    types: [ completed ]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.13.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
```

And unfortunately from some time action start and fails:

```bash
2021-05-06T03:02:10.382Z INFO  Event name: pull_request
2021-05-06T03:02:10.730Z INFO  Updating PR #197 Bump dotenv from 8.2.0 to 9.0.0
2021-05-06T03:02:10.730Z INFO  No update done due to PR mergeable_state unstable
2021-05-06T03:02:10.730Z INFO  Merging PR #197 Bump dotenv from 8.2.0 to 9.0.0
2021-05-06T03:02:10.730Z INFO  PR is probably ready: mergeable_state: unstable
2021-05-06T03:02:10.845Z INFO  Failed to merge PR: Resource not accessible by integration
2021-05-06T03:02:10.845Z INFO  Retrying after 5000 ms ... (1/6)
2021-05-06T03:02:16.159Z INFO  Failed to merge PR: Resource not accessible by integration
2021-05-06T03:02:16.159Z INFO  Retrying after 5000 ms ... (2/6)
2021-05-06T03:02:21.430Z INFO  Failed to merge PR: Resource not accessible by integration
2021-05-06T03:02:21.430Z INFO  Retrying after 5000 ms ... (3/6)
2021-05-06T03:02:26.787Z INFO  Failed to merge PR: Resource not accessible by integration
2021-05-06T03:02:26.787Z INFO  Retrying after 5000 ms ... (4/6)
2021-05-06T03:02:32.074Z INFO  Failed to merge PR: Resource not accessible by integration
2021-05-06T03:02:32.074Z INFO  Retrying after 5000 ms ... (5/6)
2021-05-06T03:02:38.047Z INFO  Failed to merge PR: Resource not accessible by integration
2021-05-06T03:02:38.047Z INFO  Retrying after 5000 ms ... (6/6)
2021-05-06T03:02:43.396Z INFO  Failed to merge PR: Resource not accessible by integration
2021-05-06T03:02:43.396Z INFO  PR could not be merged after 6 tries
```

But when I manually re-run job it successfully run and merge request.

Can you please point me out where am I wrong or what should I fix to solve this issue?

Thanks!

**Comment by SerenModz21** [comment] 2021-05-25 08:22
Hey @rosolko, I also had this issue but all I had to do was go to the repository settings and disable "Restrict editing to collaborators only" under the features due to the github-actions user not being a collaborator

**Comment by pascalgn** [comment] 2021-06-25 21:27
I think this is still not fixed, but the error is quite hard to reproduce and it's a long time since there was any activity here. I will close this issue for now, but if you have any new information or need any help, feel free to reopen this issue!

**Closed by pascalgn** 2021-06-25 21:27 UTC

**Comment by RebeccaStevens** [comment] 2021-08-02 00:32
@pascalgn I'm getting this issue too now. [Here's a link to one of the workflows](https://github.com/jonaskello/eslint-plugin-functional/runs/3215831200).

The workflow is also marking itself as successful despite the failure.

Additionally, before this error, I'm getting the following message as well "Skipping PR update, required label missing: automerge" despite my configure specifying a different merge label and that label being present.

**Comment by pascalgn** [comment] 2021-08-02 08:07
@RebeccaStevens This might be a different issue than the one OP is having, see https://github.com/actions/first-interaction/issues/10#issuecomment-545576314 So it might be because dependabot is creating the PR. The only possible workaround I know of is using a personal access token instead.

Regarding the "Skipping PR update, required label missing: automerge" message, it's a bit confusing, because there are two functionalities, both using the same label ("automerge") by default. So you can ignore this message.

Regarding the successful exit code: that is intentional, so as not to mark the PR as failed. I'm not super sure if that's how it should be or not, but that's how it is for quite some time now.

Hope this helps! 🙏

**Comment by RebeccaStevens** [comment] 2021-08-02 08:21
Thanks :)

**Comment by RebeccaStevens** [comment] 2021-08-02 23:42
@pascalgn Thought you might be interested in the comment thread here: https://github.com/jonaskello/eslint-plugin-functional/issues/253#issuecomment-890952443
