### ISSUE TITLE
`automerge` merges pull request, even the checks are not passed (`PR is probably ready: mergeable_state: unstable`)

### ISSUE THREAD

**Issue by nilsreichardt** [pascalgn/automerge-action#164] opened 2021-07-01 14:49 UTC
## Description
`automerge` merges sometime the pull requests, even if the checks not are completed.

From `README.md`
> When using a personal access token (PAT) to work around the above limitation, note that when the user issuing the PAT is an administrator and branch restrictions do not include administrators, pull requests may be merged even if they are not mergeable for non-administrators (see #65).
As you can see in the settings screenshot, I enabled "Include administrators" 🤔

It merges the pull request, if the required check (`label-pr`) is completed.

![image](https://user-images.githubusercontent.com/24459435/124146285-e90b2e00-da8d-11eb-9a87-51b606f29296.png)

### Logs
```
Run pascalgn/automerge-action@v0.14.2
2021-07-01T14:41:33.965Z INFO  Event name: pull_request
2021-07-01T14:41:34.677Z INFO  Updating PR #414 ci(flutter): integration test only on `main`
2021-07-01T14:41:34.677Z INFO  No update done due to PR mergeable_state blocked
2021-07-01T14:41:34.678Z INFO  Merging PR #414 ci(flutter): integration test only on `main`
2021-07-01T14:41:34.678Z INFO  Current PR status: mergeable_state: blocked
2021-07-01T14:41:34.678Z INFO  Retrying after 5000 ms ... (1/6)
2021-07-01T14:41:40.016Z INFO  PR is probably ready: mergeable_state: unstable
2021-07-01T14:41:41.586Z INFO  PR successfully merged!
```

### `automerge` file
```yaml
name: automerge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.pull_request.labels.*.name, 'auto-merge') &&
      github.event.pull_request.draft == false
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.2"
        env:
          # We need to use a personal access token (it's the Nils access token),
          # because the GitHub Actions are not able to merge a PR, when protect
          # our branch (Restrict who can push to matching branches). 
          GITHUB_TOKEN: "${{ secrets.AUTOMERGE_TOKEN }}"
          MERGE_LABELS: "auto-merge"
          UPDATE_LABELS: "auto-merge"
          MERGE_COMMIT_MESSAGE: "pull-request-title-and-description"
          MERGE_METHOD: "squash"
```

### Protected Branch Settings
![image](https://user-images.githubusercontent.com/24459435/124144465-49996b80-da8c-11eb-8b9c-47bbae79aebb.png)

**Comment by pascalgn** [comment] 2021-09-03 17:47
From the README:

>When the pull request is ready, it will automatically be merged. **The action will only wait for status checks that are marked as required in the branch protection rules**

Does this help already? 😅

**Comment by pascalgn** [comment] 2021-11-17 17:57
Somehow those 2 screenshots don't match. If an action is marked as required in the branch protection rules, it should also be shown with a "Required" text in the status overview, like here:

![image](https://user-images.githubusercontent.com/432333/142255768-4aa28fc0-b29a-4aca-9d68-d0292cfeb4bf.png)

**Comment by tehKapa** [comment] 2021-11-17 20:53
I think once merged that info disappears. As you can see from this screenshot there are workflows required 

<img width="962" alt="Screenshot 2021-11-17 at 21 44 24" src="https://user-images.githubusercontent.com/6388707/142280694-b9945a94-578f-402f-b339-70a55406c43f.png">

**Comment by pascalgn** [comment] 2021-11-17 20:59
OK, then maybe the issue could be that the user "hospitalrunbot" you're using to run automerge-action maybe has admin rights on the repository and thus may bypass failed required checks?

**Comment by tehKapa** [comment] 2021-11-17 21:09
> OK, then maybe the issue could be that the user "hospitalrunbot" you're using to run automerge-action maybe has admin rights on the repository and thus may bypass failed required checks?

Good point. I'll see if it's due to that

**Comment by benjaminhobbs** [comment] 2021-12-23 19:13
This seems to be a dupe of #65

**Comment by pascalgn** [comment] 2022-10-17 17:55
I think this is not yet fixed, or at least it's not clear what the cause for the problem is. However, it's a long time since there was some activity in this issue, so I will close it for now. If you have any new information or need any help, feel free to reopen this issue!

**Closed by pascalgn** 2022-10-17 17:55 UTC
Labels: bug
