### ISSUE TITLE
Old configuration option present: LABELS

### ISSUE THREAD

**Issue by SteveBox0** [pascalgn/automerge-action#202] opened 2022-11-20 16:27 UTC
I am getting "`ERROR Old configuration option present: LABELS`" but the action workflow does not have any labels present. Any suggestions to fix this?

```
      - name: Merge pull requests (automerge-action)
        uses: pascalgn/automerge-action@v0.15.5
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: squash
          MERGE_DELETE_BRANCH: true
```

**Comment by pascalgn** [comment] 2023-02-18 13:56
Could you try adding a run step which just runs `env`? That maybe gives a hint of what environment variables are defined. Maybe you are using a custom VM image?

**Comment by pascalgn** [comment] 2023-04-15 13:49
I think this is not yet fixed, or at least it's not clear what the cause for the problem is. However, it's a long time since there was some activity in this issue, so I will close it for now. If you have any new information or need any help, feel free to reopen this issue!

**Closed by pascalgn** 2023-04-15 13:49 UTC
