### ISSUE TITLE
Add option to not merge if other checks fails or specified number of reviews is not met

### ISSUE THREAD

**Issue by K-denno** [pascalgn/automerge-action#90] opened 2020-07-08 07:54 UTC

**Comment by AArnott** [comment] 2020-07-27 22:34
What are "other checks"?

In my case, the merge completed before checks were even completed.
[This PR](https://github.com/AArnott/pr-autocomplete-scratch/pull/1) completed nearly immediately after I applied the `automerge` label. The [GitHub Action log](https://github.com/AArnott/pr-autocomplete-scratch/runs/916605216?check_suite_focus=true) stated:

```
INFO  Event name: pull_request
INFO  Updating PR #1 line change
INFO  No update done due to PR mergeable_state unstable
INFO  Merging PR #1 line change
INFO  PR is probably ready: mergeable_state: unstable
INFO  PR successfully merged!
```

What does "unstable" mean? If that means "checks are not completed", how can I get it to *not* merge in that state?

**Comment by pascalgn** [comment] 2020-07-28 20:01
See here for docs about mergeable_state: https://developer.github.com/v4/enum/mergestatestatus/

If you don't want the action to merge then, set the checks to required, as stated in the README:

>A pull request is considered ready when:
>2. the required checks have passed (if enabled in the branch protection rules)

**Comment by AArnott** [comment] 2020-07-29 04:34
@pascalgn thanks. Do you mind if I ask how is your github action gets triggered when checks status changes? In all of my testing, I can't get my GitHub workflow triggered based on checks completing on the pr.

**Comment by pascalgn** [comment] 2020-09-29 20:44
I think this is not yet fixed, or at least it's not clear what the cause for the problem is. However, it's a long time since there was some activity in this issue, so I will close it for now. If you have any new information or need any help, feel free to reopen this issue!

**Closed by pascalgn** 2020-09-29 20:44 UTC
