### ISSUE TITLE
How to depend on successful tests?

### ISSUE THREAD

**Issue by jaraco** [pascalgn/automerge-action#137] opened 2020-12-22 22:30 UTC
I followed the usage docs and created a new action in my project, but when I did and tried to use automerge, it merged before the tests ran:

![image](https://user-images.githubusercontent.com/308610/102937432-22783680-4478-11eb-94b8-00bbe18dd512.png)

Presumably projects don't need an automerge action that's enacted immediately. What are the steps necessary to gate on tests passing? Given that's probably the most common usage scenario, could the usage be updated to include this important configuration detail (or point to an example that implements it that way)?

**Comment by luanraithz** [comment] 2020-12-23 12:23
Can't you protect your main branch by adding the required status checks?

https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-required-status-checks

**Comment by jaraco** [comment] 2020-12-23 15:36
Thanks Luan for the response.

> Can't you protect your main branch by adding the required status checks?

Yes, perhaps, but that will be rather tedious to accomplish across dozens of projects, especially if it needs to be done manually through the UI. Requiring a separate, manual step opens up opportunity for misconfiguration.

Additionally, adding constraints on particular branches adds technical debt to those repositories. For example, this repository recently migrated from `master` to `main` for the default branch. Having rules dependent on these branch names adds to the complexity of managing such branches.

Ideally, I'd like a way that committing a change to the repository would enable the automerge functionality and gate them on the tests and work with a repository that's configured with the default settings.

Is requiring status checks the recommended procedure for using automerge? If so, I'd expect that prerequisite to be documented in the Usage.

**Comment by pascalgn** [comment] 2020-12-30 12:00
Duplicate of #118

**Closed by pascalgn** 2020-12-30 12:00 UTC

**Comment by jaraco** [comment] 2020-12-30 15:43
Would you consider accepting a pull request that updates the Usage documentation to add "enable protected branches and required checks" as a prerequisite step?

**Comment by pascalgn** [comment] 2020-12-30 16:24
I've updated the README a bit

**Comment by jaraco** [comment] 2020-12-30 16:43
I've also learned that although it's possible to enable these checks through the API, [it's not possible to know the names of the checks](https://github.community/t/set-all-status-checks-to-be-required-as-branch-protection-using-the-github-api/119493) to know which to enable. They must be enabled one-by-one manually through the web UI :(.

This constraint is enough of an impediment that I'll probably not be able to use this feature until there's better support for automation.

**Comment by jaraco** [comment] 2020-12-30 16:49
> I've updated the README a bit

Thanks for that. I still think it would be useful for the Usage section to have a prerequisite step, something like "first configure the repo with protected branches and required checks." For me, the nuances of setting up protected branches still feels hidden in the introductory section, and without a careful reading of that section, it's not clear that if applied to a repository configured with the default settings, the automerge action is unlikely to work as intended. It's a _necessary_ step to first configure some branch protection with status checks.
