### ISSUE TITLE
Status check not triggering

### ISSUE THREAD

**Issue by mustafashabib** [pascalgn/automerge-action#153] opened 2021-05-19 15:00 UTC
Hey all - I'm sure this is documented somewhere but having trouble figuring something out and thought to ask.

Our config looks like this: 
```
name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.1"
        env:
          GITHUB_TOKEN: "${{ secrets.AUTOMERGE_ACCESS_TOKEN }}"
          MERGE_LABELS: "automerge,!work in progress,!wip"
          MERGE_REMOVE_LABELS: "automerge"
          MERGE_METHOD: "squash"
          MERGE_FORKS: "false"
          UPDATE_LABELS: "automerge"

```

And I'm noticing that automerge is not triggering when all status checks have completed. This means that if you give a review to a PR and "approve" it but one of our status checks is still running (unit tests or something) then it doesn't actually automerge it when that check completes. Is that something due to how my status check is triggered on my build server or something else I need to do in my automerge config?

Thanks

**Comment by liiri** [comment] 2021-05-23 09:06
I'm experiencing this too. Any workaround anyone?

**Comment by pascalgn** [comment] 2021-05-26 20:10
The GH API is sometimes a bit unreliable/slow when it comes to PR "readiness" checking. So if possible, you could try to use the functionality that is now included in GH directly: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request

If you want to investigate this issue further, there was an issue that prevented debug logs to be enabled. So you would need to update to version 0.14.2 and then enable debugging as described in the README https://github.com/pascalgn/automerge-action#debugging and see if this gives any clues 🙏

**Comment by pascalgn** [comment] 2021-06-25 21:27
I think this is still not fixed, but the error is quite hard to reproduce and it's a long time since there was any activity here. I will close this issue for now, but if you have any new information or need any help, feel free to reopen this issue!

**Closed by pascalgn** 2021-06-25 21:27 UTC

**Comment by mrmeyers99** [comment] 2021-08-16 12:51
I'm experiencing this as well.  I don't know if debug logs would help since it seems like the automerge workflow isn't being triggered at all when the check suite is complete.

**Comment by hieucd04** [comment] 2021-08-19 09:49
According to GitHub docs: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#check_suite

> `check_suite`
> blah ... blah ...
> 
> Note: This event will only trigger a workflow run if the workflow file is on the default branch.

Although you can configure it, most of the time, your default branch will be `master` or `main`. And your pull requests must, obviously, be from a different branch. Thus, the `check_suite` event will, 99% of the times, not trigger for your pull request. Same for `status` event.

**Comment by pascalgn** [comment] 2021-08-19 10:23
The docs are a bit confusing there, I think, but what they mean is: the workflow _file_ needs to be on the default branch. So if you change _the workflow file_ in a PR, the status check will still trigger the workflow using the workflow file from the default branch. But it will trigger! For "normal" PRs that don't change the workflow file, the status check is triggered normally, same as other events

**Comment by hieucd04** [comment] 2021-08-19 13:32
I'm not native English speaker so I might misunderstand English, sometimes 😄 

> if you change the workflow file in a PR, the status check will still trigger the workflow using the workflow file from the default branch

But according to the docs: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#example-using-multiple-events-with-activity-types-or-configuration 

> The following steps occur to trigger a workflow run:
> 
> ...
> 
> 2. The .github/workflows directory in your repository is searched for workflow files at the associated commit SHA or Git ref. The workflow files must be present in that commit SHA or Git ref to be considered.
> 
>     For example, if the event occurred on a particular repository branch, then the workflow files must be present in the repository on that branch.
> 
> ...

I just tested it on my private repo by simply adding the below snippet to one of my workflow files (*.yml) and created a PR which, in turn, triggered the same workflow and I could see the echo in logs
``` diff
+ - name: Echo
+   run: echo "Test"
```
