### ISSUE TITLE
Bug: Instead of removing the label from the PR, it deletes the label from the repo entirely

### ISSUE THREAD

**Issue by iansan5653** [pascalgn/automerge-action#80] opened 2020-05-21 16:32 UTC
I have `MERGE_REMOVE_LABELS` set to configure the bot to remove the `automerge` label from the PR after merging it. This it does successfully, but not by removing the label from the PR. Instead, it deletes the label from the workspace entirely, so I have to create a new label every single time I want to auto merge a PR. Also, I can't have two automerged queued because the label will get deleted when the first is merged.

Here's my entire config:
```yml
name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@80acb0f883348dcfd0e526288f7d27a12b9333be"
        env:
          GITHUB_TOKEN: "${{secrets.BOT_TOKEN}}"
          MERGE_REMOVE_LABELS: automerge
          MERGE_METHOD: squash
          MERGE_DELETE_BRANCH: true
```

**Comment by pascalgn** [comment] 2020-05-21 18:40
Ah, yes, that's a bug, unfortunately, but there's no solution yet. See #56 for more information!

**Comment by r-plus** [comment] 2020-06-03 10:26
Hi @pascalgn 

I also see this issue.

I'm thinking using `deleteLabel` method on https://github.com/pascalgn/automerge-action/blob/master/lib/merge.js#L107 is the cause.

from octokit docment, https://octokit.github.io/rest.js/v17#issues-remove-label
We should use `removeLabel` method instead for it, isn't it?

**Comment by pascalgn** [comment] 2020-06-03 11:12
wow, that's embarrassing! 😄  Yes, of course, we should use removeLabel, not really sure why we implemented this with deleteLabel. If you want, you can create a PR for it, otherwise I will fix it today or tomorrow! 👍

**Comment by r-plus** [comment] 2020-06-03 12:21
Thanks for your response, I can wait your fix 😆

**Comment by r-plus** [comment] 2020-06-04 16:53
Nice fix 👍

**Comment by pascalgn** [comment] 2020-06-19 19:32
I think this is fixed now. However, feel free to reopen this or create a new issue if you disagree or if there are any other problems! 👍

**Closed by pascalgn** 2020-06-19 19:32 UTC
