### ISSUE TITLE
Auto merge when check not complete

### ISSUE THREAD

**Issue by phamleduy04** [pascalgn/automerge-action#121] opened 2020-11-05 15:34 UTC
Hello, I am currently using Travis CI and GitHub actions to test my application. And I use automerge-action for dependencies update. But when the GitHub actions check successful (Travis not done), it auto-merged it, and that makes my checks broken!
<img width="872" alt="Screen Shot 2020-11-05 at 9 32 32 AM" src="https://user-images.githubusercontent.com/32657584/98261387-06611a00-1f4a-11eb-8532-744f961f5a20.png">
<img width="867" alt="Screen Shot 2020-11-05 at 9 33 34 AM" src="https://user-images.githubusercontent.com/32657584/98261393-08c37400-1f4a-11eb-9fea-08bf4a5fbce7.png">
Is there a way to make automerge to wait for all checks done? Thanks a lot!

**Comment by pascalgn** [comment] 2020-11-05 18:26
Duplicate of #118

**Closed by pascalgn** 2020-11-05 18:26 UTC
