### ISSUE TITLE
When using merge retries, if the label is removed after the action started, merge will still happen

### ISSUE THREAD

**Issue by jamiepinheiro** [pascalgn/automerge-action#38] opened 2019-12-04 15:09 UTC

**Comment by pascalgn** [comment] 2019-12-05 19:55
Yes, that's true, but I don't consider it unexpected behaviour per se, I think it depends. If you provide a PR for the issue, I'm happy to have a look!

**Comment by pascalgn** [comment] 2020-02-05 17:40
I'm closing this now, because I don't think it's too important. Always feel free to re-open it and if you provide a PR, I will be happy to have a look!

**Closed by pascalgn** 2020-02-05 17:40 UTC

**Comment by karfau** [comment] 2020-02-07 21:16
FYI: One way I'm aware of how to do that, would be to make a call to github api, before triggering anything.
Could be done by an action that is triggered before this one, that set's an output so that the automerge action is only triggered when the label is still present.

But even that would mean once the automerge action starts (e.g. it's retry mechanism), it can not be stopped by removing the label...
