### ISSUE TITLE
TimeoutError at Object.fetchUntilMergeBase

### ISSUE THREAD

**Issue by dvyukov** [pascalgn/automerge-action#115] opened 2020-10-04 07:02 UTC
Hello,

I've tried to use this action and it fails for me. Not sure if I am doing something wrong, or there is an issue with the action. Will appreciate any help.

PR that adds the action is:
https://github.com/google/syzkaller/pull/2169

I always fails with (tried to re-run several times):
```
INFO  Updating PR #2169 .github/workflows: add auto-merge action
ERROR TimeoutError
    at Object.fetchUntilMergeBase (/usr/local/share/.config/yarn/global/node_modules/automerge-action/lib/git.js:116:9)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

Current version of the config is:
```
name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.11.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD_LABELS: "autocommit=rebase,autosquash=squash"
          MERGE_METHOD_LABEL_REQUIRED: true
          UPDATE_METHOD: "rebase"
          UPDATE_LABELS: ""
```

**Comment by pascalgn** [comment] 2020-10-05 16:17
That's weird, it means there's a timeout when trying to find the common merge base. Could you rebase your PR onto the latest master branch and then try again?

**Comment by dvyukov** [comment] 2020-10-05 16:30
Same result with a new PR on the new latest HEAD (I believe the previous one was also on HEAD):
https://github.com/google/syzkaller/pull/2174/checks?check_run_id=1210285398

**Comment by pascalgn** [comment] 2020-10-22 16:38
Could you try to enable debug logging as described here? https://github.com/pascalgn/automerge-action#debugging

**Comment by dvyukov** [comment] 2020-10-22 20:28
Here is the result:
https://github.com/google/syzkaller/pull/2174/checks?check_run_id=1294732228

**Comment by pascalgn** [comment] 2021-06-25 21:23
I think this is still not fixed, but the error is quite hard to reproduce and it's a long time since there was any activity here. I will close this issue for now, but if you have any new information or need any help, feel free to reopen this issue!

**Closed by pascalgn** 2021-06-25 21:23 UTC
