### ISSUE TITLE
Failed to merge PR: Changes must be made through the merge queue

### ISSUE THREAD

**Issue by larabear** [pascalgn/automerge-action#235] opened 2023-07-25 22:07 UTC
The branch has "Require merge queue" setting on, and I'm getting the error "Failed to merge PR: Changes must be made through the merge queue". How can I configure the workflow in order to merge the PR with merge queue?

Here's my step:

```
...
      - name: Merge
        uses: pascalgn/automerge-action@v0.14.3
        if: steps.waitforstatuschecks.outputs.status == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: ""
          MERGE_METHOD: squash
```

**Comment by pascalgn** [comment] 2024-01-08 20:17
When adding a PR to the merge queue, it will be merged automatically (together with other PRs in the queue).

Adding a PR to the queue is only 1 click.

I'm not quite sure where you need automerge-action here? I think if you use GH's merge queue, you don't need it.

**Comment by pascalgn** [comment] 2024-04-11 21:30
I think this is not yet fixed, or at least it's not clear what the cause for the problem is. However, it's a long time since there was some activity in this issue, so I will close it for now. If you have any new information or need any help, feel free to reopen this issue!

**Closed by pascalgn** 2024-04-11 21:30 UTC
